FROM ocaml/opam2
RUN sudo apt update
RUN sudo apt install -y m4 perl libgmp-dev pkg-config zlib1g-dev
RUN opam remote add upstream https://opam.ocaml.org
RUN opam update && opam upgrade
WORKDIR "$HOME"
RUN sudo apt install -y python python-pip
RUN pip install jupyter
RUN sudo apt install wget
RUN echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" | sudo tee -a /etc/apt/sources.list
RUN wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
RUN sudo apt install -y libzmq3-dev
RUN opam install base merlin jupyter
ENV PATH=$PATH:~/.local/bin
ENTRYPOINT ["python", "/home/opam/.local/bin/jupyter", "notebook", "--ip=0.0.0.0"]
